PPW_Project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('projects/', include('projects.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('matakuliah.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='main'),
]

matakuliah/urls.py
from django.urls import path

from . import views

app_name = 'matakuliah'

urlpatterns = [
    path('', views.matkul_view, name='matkul'),
    path('add/', views.form_view, name='add'),
    path('detail/<int:id>', views.detail_view, name='detail'),

]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.index, name='projects'),

]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='story1'),

]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7, name='story7'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.story8, name='story8'),
    path('data/', views.fungsi_data_story8, name='fungsi_data_story8'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
]

main/models.py
from django.db import models

# Create your models here.

matakuliah/models.py
from django.db import models

# Create your models here.
class Matkul (models.Model):
    Mata_Kuliah = models.CharField(max_length = 30, default=" ")
    Dosen_Pengajar = models.CharField(max_length = 25, default=" ")
    SKS = models.DecimalField(max_digits = 1, decimal_places=0, default=3)
    deskripsi = models.TextField()
    kelas = models.CharField(max_length = 25, default=" ")

projects/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

matakuliah/forms.py
from django import forms

from .models import Matkul

class InputForm(forms.ModelForm):
    class Meta :
        model = Matkul
        fields = [
            'Mata_Kuliah', 'Dosen_Pengajar', 'SKS', 'kelas','deskripsi',
        ]

        widgets = {
            'Mata_Kuliah' : forms.TextInput(attrs={'class': 'form-control'}),
            'Dosen_Pengajar' : forms.TextInput(attrs={'class': 'form-control'}),
            'SKS' : forms.TextInput(attrs={'class': 'form-control'}),
            'kelas' : forms.TextInput(attrs={'class': 'form-control'}),
            'deskripsi' : forms.Textarea(attrs={'class': 'form-control'}),
        }

story9/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class CreateUserForm(UserCreationForm) :
    class Meta :
        model = User
        fields = [
            'username', 'email', 'password1', 'password2'
        ]

main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/index.html')

matakuliah/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import InputForm
from .models import Matkul
# Create your views here.

def form_view(request) :
    form = InputForm()
    if (request.method == 'POST') :
        form = InputForm(request.POST or None)
        if (form.is_valid):
            form.save()
            return redirect('matakuliah:matkul')
    context = {'input_form' : form}

    return render(request, 'matakuliah/form.html', context)

def matkul_view(request):
    matkuls = Matkul.objects.all()
    context = {}
    context['matkuls'] = matkuls

    if request.method == 'POST' :
        if request.POST.get("delete") :
            Matkul.objects.get(id=request.POST.get("delete")).delete()
            return redirect('matakuliah:matkul')

        elif request.POST.get("add") :
            return redirect('matakuliah:add')
        
        elif request.POST.get("detail"):
            Matkul.objects.get(id=request.POST.get("detail"))
            return redirect('matakuliah:detail')
    
    return render(request, "matakuliah/index.html", context)

def detail_view(request,id):
    matkul = Matkul.objects.get(id=id)
    context = {}
    context['matkul'] = matkul

    return render(request, "matakuliah/desc.html", context)


    

projects/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'projects/Page2.html')

story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story1/index.html')

story7/views.py
from django.shortcuts import render

# Create your views here.

def story7(request) :
    return render(request, 'story7/index.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def story8(request) :
    return render(request, 'story8/index.html')

def fungsi_data_story8(request) :
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    urlReturn = requests.get(url)
    data = json.loads(urlReturn.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def user_login(request) :
    if request.method == 'POST' :
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None :
            login(request, user)
            return redirect('main:main')

    context = {}
    return render(request, 'story9/login.html', context)

def user_register(request) :
    if request.method == 'POST' :
        form = CreateUserForm(request.POST)
        if form.is_valid() :
            form.save()
            return redirect('story9:login')
    else :
        form = CreateUserForm()

    context = {'form':form}
    return render(request, 'story9/register.html', context)

def user_logout(request) :
    logout(request)
    return redirect('main:main')

main/templates/main/index.html
{% extends "base.html" %}
{% load static %}

<html>


<body>
{% block content %}
<header>

    <h1 class="title">PROFILE</h1>

    <div class="row">

        <div class="column">
        <img src="{% static 'main\foto.png' %}" style="width:225px; height:225px;">
        </div>

        <div class="column middle">
        <h2 id="name-profile"class="title">Muhammad Rakha <br> <span>Zachrie</span></h2> 
        <hr>
        <h3 id="name-profile" class="column middle">Mahasiswa</h3>
        </div>
    </div>




</header>

<section>
<div class="row">

    <div class="column">
        <h3> About Me </h3>
    </div>

    <div class="column middle">
        <p> Saya merupakan mahasiswa tahun kedua di Universitas Indonesia. Saya menyukai games dan sepakbola.</p>
    </div>

</div>

<div class="row">
    <div class="column">
        <h3> Education </h3>
    </div>

    <div class="column middle">
        <ul class="list-unstyled">
            <li>SDN Bambu Apus <small class="text-muted">(2006 - 2012)</small></li>
            <li>SMPN 20 Jakarta <small class="text-muted">(2012 - 2015)</small></li>
            <li>SMAN 48 Jakarta <small class="text-muted">(2015 - 2018)</small></li>
            <li>Universitas Indonesia <small class="text-muted">(2019 - Present)</small></li>
        </ul>
    </div>
</div>

</section>
    
<footer>

<div class="row">

    <div class="column logo">
        <a href="https://www.instagram.com/rakhazachrie"><img src="{% static 'main\IG.png' %}" style="width:75px;height:75px;" class="rounded-circle"></a>
    </div>

    <div class="column logo">
        <a href="https://www.linkedin.com/in/rakha-zachrie/"><img src="{% static 'main\LinkedIn.jpg' %}" style="width:75px;height:75px;" class="rounded-circle"></a>
    </div>

</div>
</footer>
{% endblock content %}
</body>
</html>

matakuliah/templates/matakuliah/desc.html
{% extends "base.html" %}
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'matakuliah\style.css' %}">
    </head>
    {% block content %}
    <body>
        <br>
        <h3 class="title"> Deskripsi Mata Kuliah</h3>
        <br>
            <div class="shadow p-3 mb-5 bg-white rounded">
                <h4 style="font-family:Prompt;"> {{ matkul.Mata_Kuliah }}</h4>
                <p style="font-family:Prompt;"> {{ matkul.deskripsi }}</p>
                <p style="font-family:Prompt;"> Kelas : {{ matkul.kelas }}</p>
            </div>
    </body>
    {% endblock content %}

matakuliah/templates/matakuliah/form.html
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    </head>
    <body>
        <h3 style="text-align: center;"> Daftar Mata Kuliah </h3>
        <div class="form-group">
            <form action="" method="post">
                {% csrf_token %}
                {{ input_form.as_p}}
                <input type="submit" value="Submit">
            </form>
        </div>
    </body>
</html>

matakuliah/templates/matakuliah/index.html
{% extends "base.html" %}
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'matakuliah\style.css' %}">

    </head>
    {% block content %}
    <body>
        <br>
        <h3 class="title"> Daftar Mata Kuliah</h3>
        <br>
        {% for i in matkuls %}
        <div class="container-fluid">
                <h3 style="font-family:Prompt;">
                    <a href= "{% url 'matakuliah:detail' i.id %}" style="color:black;">
                        {{ i.Mata_Kuliah }}
                    </a>
                    <small class="text-muted">{{ i.SKS }} SKS</small>
                </h3>
            <p style="font-family:Prompt;">Dosen Pengajar : {{ i.Dosen_Pengajar }}</p>

            <form method="POST">
                {% csrf_token %}
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="submit" name="delete" value= {{i.id}}  class="btn btn-secondary btn-sm">DELETE</button> 
                </div>
            </form>
            <br>

        </div>
        {% endfor %}
        <br>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" name="add" value="add" class="btn btn-secondary btn-lg btn-block"> ADD </button>            
        </form>
    </body>
    <button type="submit" name="detail" value= {{i.id}} style="border: none; outline: none; background: none; text-align: left;">
        {{ i.Mata_Kuliah }}
    </button>
    {% endblock content %}

projects/templates/projects/Page2.html
{% extends "base.html" %}
{% load static %}
<html>
    
    <body>
    {% block content %}

        <h2 class="title">Abilities</h2>

        <table id="center" class="table table-borderless">
            <thead>
              <tr>
                <th scope="col">Skills</th>
                <th scope="col">Languages</th>
                <th scope="col">Tools</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Active listening</td>
                <td>Indonesia</td>
                <td>Ms.Office</td>
              </tr>
              <tr>
                <td>Programming Languages<br>(java, python, html)</td>
                <td>English</td>
                <td>Adobe Photoshop</td>
              </tr>
              <tr>
                <td>Leadership</td>
                <td>German</td>
                <td>Windows</td>
              </tr>
            </tbody>
        </table>

        <h2 class="title">Projects & Experiences</h2>

        <div class="row row-cols-1 row-cols-md-2">
            <div class="col mb-4">
              <div class="card">
                <img src="{% static 'projects\traveloka.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Project 1</h5>
                  <p class="card-text">Deskripsi</p>
                </div>
              </div>
            </div>
            <div class="col mb-4">
              <div class="card">
                <img src="{% static 'projects\gojek.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Project 2</h5>
                  <p class="card-text">Deskripsi</p>
                </div>
              </div>
            </div>
            <div class="col mb-4">
              <div class="card">
                <img src="{% static 'projects\tokopedia.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Experience 1</h5>
                  <p class="card-text">Deskripsi</p>
                </div>
              </div>
            </div>
            <div class="col mb-4">
              <div class="card">
                <img src="{% static 'projects\ruangguru.png' %}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Experience 2</h5>
                  <p class="card-text">Deskripsi</p>
                </div>
              </div>
            </div>
        </div>
      </body>
      {% endblock content %}
</html>

story1/templates/story1/index.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'story1/style.css' %}">
    </head>
<body>
    <img src="{% static 'story1/foto.png' %}" style="width:250px; height:250px;">


    <h3> About Me </h3>
    <p> Saya merupakan mahasiswa Universitas Indonesia Fakultas Ilmu Komputer 2019</p>

    <h3> Profile </h3>

    <p>
     Nama        : Muhammad Rakha Zachrie<br>
     NPM         : 1906353795<br>
     Angkatan    : 2019<br>
     Hobi        : Bermain Game<br>
     Universitas Indonesia Fakultas Ilmu Komputer
    </p>


    <h3> Educations</h3>

    <table >
        <tr>
            <th>Pendidikan</th>
            <th>Tahun</th> 
        </tr>
        <tr>
            <td>SDN 01 Bambu Apus</td>
            <td>2006 - 2012</td>
        </tr>
        <tr>
            <td>SMPN 20 Jakarta</td>
            <td>2012 - 2015</td>
        </tr>
        <tr>
            <td>SMAN 48 Jakarta</td>
            <td>2015 - 2018</td>
        </tr>
        <tr>
            <td>Universitas Indonesia</td>
            <td>2019 - Sekarang</td>
        </tr>
    </table>

    <h3 style> Contact </h3>
    <a href="https://www.instagram.com/rakhazachrie"><img src="{% static 'story1/IG.png' %}" style="width:42px;height:42px;"></a>


</body>
</html>

story7/templates/story7/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h2 class="title"> Story 7 Accordion</h2>

<br>

<div class="accordion">
  <div class="accord-part">
    <div class="accord-header">My Activity
      <button type="button"  class="up">^</button> <button type="button" class="down">v</button>
    </div>
    <div class="accord-content">Kegiatanku saat ini adalah sebagai mahasiswa Fakultas Ilmu Komputer angkatan 2019 di Universitas Indonesia.</div>
  </div>

  <div class="accord-part">
    <div class="accord-header">My Experience
      <button type="button" class="up">^</button> <button type="button" class="down">v</button>
    </div>
    <div class="accord-content">
      <li>Experience 1</li>
      <li>Experience 2</li>
      <li>Experience 3</li>
    </div>
  </div>

  <div class="accord-part">
    <div class="accord-header">My Achievement
      <button type="button" class="up">^</button> <button type="button" class="down">v</button>
    </div>
    <div class="accord-content">
      <li>Achievement 1</li>
      <li>Achievement 2</li>
      <li>Achievement 3</li>
    </div>
  </div>

  <div class="accord-part">
    <div class="accord-header">My Hobby
      <button type="button" class="up">^</button> <button type="button" class="down">v</button>
    </div>
    <div class="accord-content">
      <li>Bermain Game</li>
      <li>Menonton Sepakbola</li>
      <li>Menonton YouTube</li>
      <li>Ngoding</li>
  </div>
  
</div>


{% endblock %}


{% block script %}
<script src= "{% static 'story7/event.js' %}"></script>
{% endblock %}

story8/templates/story8/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<input class="keyword" placeholder="Search books">
<h2 class="title">Daftar Buku</h2>
<br>

<br>

<table class="list-books">

</table>

{% endblock %}

{% block script %}

<script src= "{% static 'story8/eventSearch.js' %}"></script>

{% endblock %}

story9/templates/story9/login.html
{% extends "base.html" %}

{% block content %}

<h2 class="title">Login</h2>

<br>

<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Username</label>
        <input type="text" class="form-control" id="exampleFormControlInput1" name="username">
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Password</label>
        <input type="password" class="form-control" id="exampleFormControlInput1" name="password">
    </div>

    <br>
    <p>Don't have an account? <a href="{% url 'story9:register' %}">Sign up</a></p>
    <button type="submit" class="btn btn-outline-primary">Login</button>

</form>

{% for message in messages %}
    <p>{{message}}</p>
{% endfor %}






{% endblock %}

story9/templates/story9/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<h2 class="title">Register</h2>

<br>


<form method="POST"> 
    {% csrf_token %}

    {{form|crispy}}

    <button type="submit" class="btn btn-outline-primary">Register</button>
</form>

{% endblock %}