PPW_Project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('projects/', include('projects.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('matakuliah.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='main'),
]

matakuliah/urls.py
from django.urls import path

from . import views

app_name = 'matakuliah'

urlpatterns = [
    path('', views.matkul_view, name='matkul'),
    path('add/', views.form_view, name='add'),
    path('detail/<int:id>', views.detail_view, name='detail'),

]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.index, name='projects'),

]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='story1'),

]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7, name='story7'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.story8, name='story8'),
    path('data/', views.fungsi_data_story8, name='fungsi_data_story8'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
]

main/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

matakuliah/forms.py
from django import forms

from .models import Matkul

class InputForm(forms.ModelForm):
    class Meta :
        model = Matkul
        fields = [
            'Mata_Kuliah', 'Dosen_Pengajar', 'SKS', 'kelas','deskripsi',
        ]

        widgets = {
            'Mata_Kuliah' : forms.TextInput(attrs={'class': 'form-control'}),
            'Dosen_Pengajar' : forms.TextInput(attrs={'class': 'form-control'}),
            'SKS' : forms.TextInput(attrs={'class': 'form-control'}),
            'kelas' : forms.TextInput(attrs={'class': 'form-control'}),
            'deskripsi' : forms.Textarea(attrs={'class': 'form-control'}),
        }

story9/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class CreateUserForm(UserCreationForm) :
    class Meta :
        model = User
        fields = [
            'username', 'email', 'password1', 'password2'
        ]

main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/index.html')

projects/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'projects/Page2.html')

story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story1/index.html')

story7/views.py
from django.shortcuts import render

# Create your views here.

def story7(request) :
    return render(request, 'story7/index.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def story8(request) :
    return render(request, 'story8/index.html')

def fungsi_data_story8(request) :
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    urlReturn = requests.get(url)
    data = json.loads(urlReturn.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def user_login(request) :
    if request.method == 'POST' :
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None :
            login(request, user)
            return redirect('main:main')

    context = {}
    return render(request, 'story9/login.html', context)

def user_register(request) :
    if request.method == 'POST' :
        form = CreateUserForm(request.POST)
        if form.is_valid() :
            form.save()
            return redirect('story9:login')
    else :
        form = CreateUserForm()

    context = {'form':form}
    return render(request, 'story9/register.html', context)

def user_logout(request) :
    logout(request)
    return redirect('main:main')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">


  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <a class="navbar-brand" href="#">Rakha's Story</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'main:main' %}">HOME</a></li>
          <!-- <li><a href="{% url 'projects:projects' %}">PROJECT & EXPERIENCE</a></li> -->
          <li><a href="{% url 'matakuliah:matkul' %}">MATA KULIAH</a></li>
          <li><a href="{% url 'story7:story7' %}">STORY 7</a></li>
          <li><a href="{% url 'story8:story8' %}">STORY 8</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'story9:logout' %}">LOGOUT</a></li>
            <li><a href="#">Hi {{ request.user.username }} !!</a></li>
          {% else %}
            <li><a href="{% url 'story9:login' %}">LOGIN</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</head>

<body>
  {% block content %}
  {% endblock %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  {% block script %}
  {% endblock %}
</body>

</html>